### ISSUE TITLE
You may consider using well established libraries for image augmentations.

### ISSUE THREAD

**Issue by ternaus** [gradio-app/gradio-UI#12]
It looks like you manually implement image augmentations.

You may try to look at https://github.com/albu/albumentations

**Comment by dawoodkhan82** [comment]
> It looks like you manually implement image augmentations.
> 
> You may try to look at https://github.com/albu/albumentations

Awesome, this seems very useful. Will take a look.

**Comment by rcox771** [comment]
I like albumentations too but I believe the authors are just focused on creating reusable ui components to make ML more accessible - at least that seems to be the main spirit of their message in this library. There's nothing stopping us from swapping out the guts of the functions we pass into their components and that's the point. As long as we conform to the the formats of their interfaces at the presentation layer, then almost anything is possible. Use numpy, pytorch, tensorflow, cowsays, interpretative dance, whatever ye want. The rest is plug n' chug.

-Russ
