### ISSUE TITLE
GPT 2 demo doesn't run on colab

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio-UI#21]
One of my alpha testers pointed this out, and I also experience it:

![image](https://user-images.githubusercontent.com/1778297/86502439-b5a59e80-bd68-11ea-9d2a-5dd8875f2a44.png)

**Comment by abidlabs** [comment]
Or maybe it does run, but can we hide the error?

**Comment by aliabd** [comment]
Error comes from TF==2.1, which is actually not necessary. Fixed
